plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}

mod_version = "${mod_version}-fabric${fabricVersionAppend}"
version = mod_version

stonecutter {
    constants["serene_seasons"] = project.hasProperty("fabric_serene_seasons_version")
}

repositories {
    flatDir {
        dir 'libs'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modApi("${forge_config_api_port_group}:forgeconfigapiport-fabric:${forge_config_api_port_version}") {
        exclude group: "net.fabricmc"
    }

    if (project.hasProperty("night_config_version")) {
        implementation "com.electronwill.night-config:core:${night_config_version}"
        implementation "com.electronwill.night-config:toml:${night_config_version}"
    }

    implementation("net.jodah:typetools:0.6.3")

    modImplementation "curse.maven:jade-324717:${fabric_jade_version}"
    modImplementation "curse.maven:jei-238222:${fabric_jei_version}"

    if (project.hasProperty("fabric_glitchcore_version")) {
        modImplementation "curse.maven:glitchcore-955399:${fabric_glitchcore_version}"
    }

    if (project.hasProperty("fabric_serene_seasons_version")) {
        modImplementation "curse.maven:serene-seasons-291874:${fabric_serene_seasons_version}"
    }

    modCompileOnly "curse.maven:continuity-531351:${fabric_continuity_version}"

    if (project.hasProperty("fabric_sodium_version")) {
        modRuntimeOnly "maven.modrinth:sodium:${fabric_sodium_version}"
    }

    if (project.hasProperty("fabric_indium_version")) {
        modRuntimeOnly "maven.modrinth:indium:${fabric_indium_version}"
    }

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.5")))
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/accesswideners/${accesswidener}")

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }
