# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_name=Dynamic Trees
mod_author=Ferreusveritas
mod_id=dynamictrees
credits=Current developer: MaxHyper. Development of treepacks: Harley O'Connor. Help with version ports: Nyfaria, SizeableShrimp & Harley O'Connor
license=MIT
description=Trees that grow, forests that spread...
group=com.dtteam.dynamictrees
mod_version=1.7.2
fabricVersionAppend=-BETA
forgeVersionAppend=
neoVersionAppend=
versionType=stable
fabricVersionType=beta

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
