# Common
minecraft_version=1.18.2
minecraft_version_range=[1.18.2, 1.19)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.18.2
parchment_version=2022.11.06
java_version=17
forge_config_api_port_version=3.2.4
forge_config_api_port_variant=fabric
forge_config_api_port_group=net.minecraftforge
night_config_version=3.6.3

# Fabric
fabric_version=0.77.0+1.18.2
fabric_loader_version=0.18.4

fabric_jade_version=4573438
fabric_jei_version=5106177
fabric_continuity_version=4441029

# Forge
forge_version=40.3.0
forge_loader_version_range=[40,)

forge_jade_version=5079263
forge_jei_version=8829822
forge_serene_seasons_version=3804257
forge_patchouli_version=3846086
forge_spark_version=4505375
