plugins {
    id 'multiloader-loader'
    id "net.neoforged.moddev.legacyforge"
}

mod_version = "${mod_version}-forge${forgeVersionAppend}"
version = mod_version

stonecutter {
    constants["serene_seasons"] = project.hasProperty("forge_serene_seasons_version")
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
    config "${mod_id}.forge.mixins.json"
}

legacyForge {
    enable {
        forgeVersion = "${minecraft_version}-${forge_version}"
    }

    validateAccessTransformers = true

    accessTransformers.from(project(":forge").file("src/main/resources/accesstransformers/$accesstransformer"))

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    def mainResources = project(":common").file("src/main/resources")
    def genResources = sc.node.sibling("common").project.file("src/generated/resources")

    runs {
        configureEach {
            ideName = "Forge ${it.name.capitalize()} (${project.path})"
            systemProperty "mixin.config", "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
        }

        client {
            client()
        }

        data {
            data()
            programArgument ('--all')
            programArgument ('--existing')
            programArgument (mainResources.absolutePath)
            programArgument ('--output')
            programArgument (genResources.absolutePath)
            programArgument ('--mod')
            programArgument ("${mod_id}")
        }

        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main {
    resources.srcDir("src/generated/resources")
}

tasks {
    jar {
        finalizedBy("reobfJar")

        manifest {
            attributes([
                    "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
            ])
        }
    }
}

dependencies {
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    compileOnly("org.jetbrains:annotations:24.1.0")

    modImplementation "curse.maven:jade-324717:${forge_jade_version}"
    modImplementation "curse.maven:jei-238222:${forge_jei_version}"
    modImplementation "curse.maven:serene-seasons-291874:${forge_serene_seasons_version}"

    modRuntimeOnly "curse.maven:patchouli-306770:${forge_patchouli_version}"
    modRuntimeOnly "curse.maven:spark-361579:${forge_spark_version}"

    implementation(jarJar("io.github.llamalad7:mixinextras-neoforge:0.5.5"))
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version))
    }
}

createMinecraftArtifacts {
    dependsOn ":forge:${minecraft_version}:stonecutterGenerate"
}

processResources {
    from(project(":forge").file("src/main/resources/accesstransformers/$accesstransformer")) {
        into("META-INF")
        rename { "accesstransformer.cfg" }
    }
}
