plugins {
    id("multiloader-common")
    id("fabric-loom")
}

version = "${mod_version}"

loom {
    def aw = project(":common").file("src/main/resources/META-INF/${mod_id}.accesswidener")

    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        useLegacyMixinAp = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    compileOnly "org.spongepowered:mixin:0.8.5"
    modCompileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"

    modApi("${forge_config_api_port_group}:forgeconfigapiport-${forge_config_api_port_variant}:${forge_config_api_port_version}") {
        exclude group: "net.fabricmc"
    }

    if (project.hasProperty("night_config_version")) {
        implementation "com.electronwill.night-config:core:${night_config_version}"
        implementation "com.electronwill.night-config:toml:${night_config_version}"
    }

    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    sourceSets.main.resources {
        srcDir sc.node.sibling("common").project.file("src/generated/resources")
        srcDir project(":common").file("src/localization/resources")
    }

    commonJava sourceSets.main.java.sourceDirectories.files
    commonResources sourceSets.main.resources.sourceDirectories.files

}

publishing {
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
        var mavenUsername = project.findProperty("harleyOConnorMavenUsername")?.toString() ?: System.getenv("MAVEN_USERNAME")
        var mavenPassword = project.findProperty("harleyOConnorMavenPassword")?.toString() ?: System.getenv("MAVEN_PASSWORD")
        if (mavenUsername == null || mavenPassword == null) {
            logger.log(LogLevel.WARN,"Credentials for maven not detected; it will be disabled.")
            return
        }
        maven {
            name = "HarleyOConnor"
            url = "https://harleyoconnor.com/maven"
            credentials {
                username = mavenUsername
                password = mavenPassword
            }
        }
    }
}