plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "me.modmuss50.mod-publish-plugin"
}

mod_version = "${mod_version}-neoforge${neoVersionAppend}"
version = mod_version



neoForge {
    validateAccessTransformers = stonecutter.current.isActive
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    def mainResources = project(":common").file("src/main/resources")
    def genResources = sc.node.sibling("common").project.file("src/generated/resources")
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            data()
            programArgument ('--all')
            programArgument ('--existing')
            programArgument (mainResources.absolutePath)
            programArgument ('--output')
            programArgument (genResources.absolutePath)
            programArgument ('--mod')
            programArgument ("${mod_id}")
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

}

repositories {
    flatDir {
        dir 'libs'
    }
}

dependencies {
    implementation "curse.maven:jade-324717:${neoforge_jade_version}"
    implementation "curse.maven:jei-238222:${neoforge_jei_version}"
    implementation "curse.maven:glitchcore-955399:${neoforge_glitchcore_version}"
    implementation "curse.maven:serene-seasons-291874:${neoforge_serene_seasons_version}"

    runtimeOnly "curse.maven:patchouli-306770:${neoforge_patchouli_version}"
    runtimeOnly "curse.maven:spark-361579:${neoforge_spark_version}"

    implementation "${forge_config_api_port_group}:forgeconfigapiport-neoforge:${forge_config_api_port_version}"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
